apiVersion: apps/v1
kind: Deployment
metadata:
  name: guessthenumber-py
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guessthenumber-py
  template:
    metadata:
      labels:
        app: guessthenumber-py
    spec:
      containers:
        - name: guessthenumber-py
          image: #your-duckerhub-username/guess-the-number:latest
          ports:
            - containerPort: 80
