apiVersion: apps/v1
kind: Deployment
metadata:
  name: guessthenumber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guessthenumber
  template:
    metadata:
      labels:
        app: guessthenumber
    spec:
      containers:
      - name: guessthenumber
        image: phroggiers/guesss:v5
        ports:
        - containerPort: 8080
        # Add a readiness probe to check if the app is ready
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        # Add a liveness probe to check if the app is running
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
